### ISSUE TITLE
Feature request: support for WOFF2 format

### ISSUE THREAD

**Issue by sambaldwin** [hanikesn/woff2otf#10]
[WOFF2](https://www.w3.org/TR/WOFF2) is growing in popularity. Are there any plans to add support for this file format?

**Comment by hanikesn** [comment]
WOFF2 is a a lot more complex to decode than WOFF, e.g. it uses brotli and encodes the glyphs separately. Whereas WOFF was basically a compressed version of existing font formats.

In conclusion I don't have any concrete plans to support WOFF2, but will of course accept PRs implementing it.
